language: node_js
node_js:
- '8'
cache: yarn
branches:
  only:
  - master
  - develop
env:
  dev:
  - CHANNEL_TOKEN=Cd9zDe9LZvQ5UDfVZZElDTY+0lfW26UOZ210/QMozN4o8jXjGt9ckRCCUYFv+/bZO9paIZL7b23WA2lxS+OYknIM26TYrkUxwK2Kp8/1nXPsKwkafkX2jckSggjhC9FLzA1Hio3glJsCwIM5GdeXRQdB04t89/1O/w1cDnyilFU=
  global:
  - CHANNEL_TOKEN=Cd9zDe9LZvQ5UDfVZZElDTY+0lfW26UOZ210/QMozN4o8jXjGt9ckRCCUYFv+/bZO9paIZL7b23WA2lxS+OYknIM26TYrkUxwK2Kp8/1nXPsKwkafkX2jckSggjhC9FLzA1Hio3glJsCwIM5GdeXRQdB04t89/1O/w1cDnyilFU=
  - secure: ZdS3WVw/a1Lg4bond7OOjdkkgEn2pxMXKdaAipSo8PK7tXcdSrVrWKULE8Kisez3lO4hqXzx0AqBYwHVPBkY/5yU4YtJKvZGT+XPntCzOFVDdE96fxslwehtgso9O3SwiRiAMgihhFVHIOFVrAhct1lP4FJBH1LTIP17GQGnWkBOUzli3AKVup3NKUWra77QqJO/TeiZAj6H6BQXd/93jIf97yTC9grwr/rPqEgR76bIg9JyWvzgG3qi92GmNu69RNqr7ST6FXegkcQ9JkDpXDQ6M7uziip1MtkpK56PlZZFdWaFvH8xWJi1KbOtnIu7H4Pq7wJolP91MZffi+medlEQjV1LhtfPTNH4BbxraKmuVQhf5AjgxoTpbxYijx8UHSzVfiMJMBRKy0lhj45Q5Bc7ojpxuK9cpiXKtkZ5KurV8sKWS/CPFWgAxTrK0eKhS6//w1Jb9yc/BiWt7/twJVGyxLGzQWiSYhfhDiDfm1+9vA4JVTmzjkj1C6X+PmkUJvH6qrRdqSUk6FfuoPPJfEaTPTrA+qlFIdehdTwV2lqnBi2aUi0MiV7wRVAnUE+zrTiDddseGnjCGCJl4r8IyYCwGCVrxsazGs/ayu5zJFe7rKOMs07jz2tNhGZK9v7k4l8hPBa61Q+aqHpF5OjgNOWJrl+/NyBDuR8VlzjDmf8=
deploy:
  provider: firebase
  token:
    secure: "1/hTwbbH56SyGaYNSygVcMAjt7Th-eZGtReVs-A5VWWT_v5KjH4LpgBFBF0_BH0k-Y"
  message: "start deploy chat bot to firebase"